### PR TITLE
bugReport:build hbase on spark failed

### PR DESCRIPTION
**Pull request by HZMengYue**
############ bug 1 ############
for today afternoon,i checkout a hbase branch from HuaWei-Spark,and my built command is:mvn -Pyarn -Phadoop-2.3 -Phive -Phbase -DskipTests package
but it failed,with follow info:

### CODE REVIEW

**Comment by scwf** [comment]
Hi @yzhou2001, the newest hbase branch compile failed, i fix it by update with apache/master branch and push it to hbase1 branch. If you think it is ok, i will push it to hbase branch.

**Comment by bomeng** [comment]
Use the new branch as said in my previous email.-bo-

----- Reply message -----

**Comment by scwf** [comment]
@bomeng, your newly branch cli also have problem.

**Comment by scwf** [comment]
now you all work on the HW_HBase branch?

**Comment by bomeng** [comment]
Yes, we all should work on the new branch and make it stable. It is normal to have issues after a big integration, that is why we need more tests.Please test as much as possible. I only did some limited tests.Thanks.-bo-
Date: Tue, 6 Jan 2015 23:04:12 -0800

**Comment by scwf** [comment]
but now we need a stable branch do performance test, which branch should i use?

**Comment by bomeng** [comment]
You should use the new branch whenever possible, unless it blocks you to do the test.You can also use git reset to commit "fad27762" on branch "hbase" to do the test, but that branch will be abandoned eventually. For performance test, you can still use it if the new branch blocks you.-bo-

Date: Tue, 6 Jan 2015 23:16:33 -0800

**Comment by scwf** [comment]
@bomeng and @yzhou2001, we should consider empty string in HBaseKVHelper, see a example:
table a (key int, value string) and the csv file may have empty string such as

```
1,wf
,bomeng
2,
```

**Comment by scwf** [comment]
bug report: load local will throw no such file exception

**Comment by scwf** [comment]
Now `load local` only works for local mode and I suggest use `load local` just for test use case, this is because
1 `load local` of our project is different with hive, hive's `load local` is just to copy local file to hive warehouse dir, but ours need to do encoding and bulkloading
2 `load local` performance issue, it is hard to make use of distributed compute ability of spark

so maybe we do not need support load local or just use for unit test?

**Comment by scwf** [comment]
4 And actually in Phoenix, bulk Loading via MapReduce also not support local file

**Comment by yzhou2001** [comment]
Currently we require all key columns to be non-null.  For those "bad" records, we can add some logging to keep a record/counter of the "bad" records as Hadoop M/R has been doing.

**Comment by yzhou2001** [comment]
@scwf "LOAD DATA LOCAL INPATH" is not in the design doc. Please remove it from the source and test as soon as you can. Thanks.

**Comment by yzhou2001** [comment]
Actually we could leave the codes there but will not officially support it.

**Comment by scwf** [comment]
@yzhou2001, yes i know we require all key columns to be non-null, i mean non key columns and i think that  non key columns  should support empty string, and query for these empty column will get `null`. in 
our smartcase data, there are many fields which is empty such as:
  ``` 643821006911370419575747,1875384,2,,,,,1```
BTW phoniex support this.

**Comment by scwf** [comment]
agree, Ok, i will leave the local code here, but will not officially support it.

**Comment by yzhou2001** [comment]
I'd appreciate if you or an Indian team member can fix the null non-key issue today. If not, please let us know immediately. Thanks.

**Comment by scwf** [comment]
Hi @yzhou2001, I think the fix should be:  use a special encoding and decoding for empty string with specified datatype in HbaseKVHelper, i am not sure which is a better way to encoding and decoding the empty string and i suggest @bomeng handle it since he is very familiar with this, Or @bomeng can give me some point and let me know your concern here.

**Comment by bomeng** [comment]
I will think about it and propose a solution as soon as possible. I suppose it will handle empty string (aka ""), not null string. Is it correct?

**Comment by scwf** [comment]
@bomeng yes, correct, empty string

**Comment by yzhou2001** [comment]
I already checked in a fix. The test coverage will be added.

**Comment by scwf** [comment]
@yzhou2001, report a performance issue:
Create a table with 134 fields(1 primarykey + 133nokprimarykey) cost 12s.

**Comment by bomeng** [comment]
I found the issue - it was caused by the recent change of how to get metadata table. getMetadataTable()

**Comment by scwf** [comment]
@bomeng @xinyunh @yzhou2001, performance issue:
 bulk loading have not advantage with phoniex:
```
dataset:
Size      :  586M
Rows     :  1,000,000
Columns  :   134

Phoenix      :   500 s
sparksqlhbase(presplit): 600s
sparksqlhbase(no presplit): 1372s
```
After debug and analysis, this two operation cost much time:
https://github.com/Huawei-Spark/spark/blob/HW_HBase/sql/hbase/src/main/scala/org/apache/spark/sql/hbase/execution/hbaseCommands.scala#L327
https://github.com/Huawei-Spark/spark/blob/HW_HBase/sql/hbase/src/main/scala/org/apache/spark/sql/hbase/execution/hbaseCommands.scala#L411

**Comment by scwf** [comment]
@xinyunh this is the create table cmd:

create table wftest5(id int,rk string,sid int,probeid int,interfaceid int,groupid int,ggsn_id int,sgsn_id int,session_indicator int,begin_time int,begin_time_msel int,end_time int,end_time_msel int,prot_category int,prot_type int,l7_carrier_prot int,msisdn string,imsi string,imei string,encrypt_version int,roaming_type int,roam_direction int,ms_ip string,server_ip string,ms_port int,server_port int,apn string,sgsn_sig_ip string,ggsn_sig_ip string,sgsn_user_ip string,ggsn_user_ip string,mcc string,mnc string,rat int,lac string,rac string,sac string,ci string,browser_type int,l4_ul_throughput int,l4_dw_throughput int,l4_ul_goodput int,l4_dw_goodput int,network_ul_traffic int,network_dl_traffic int,l4_ul_packets int,l4_dw_packets int,tcp_conn_states int,tcp_states int,tcp_rtt int,tcp_ul_outofsequ int,tcp_dw_outofsequ int,tcp_ul_retrans int,tcp_dw_retrans int,tcp_win_size int,tcp_mss int,tcp_conn_times int,tcp_conn_2_failed_times int,tcp_conn_3_failed_times int,host string,streaming_url string,get_streaming_failed_code int,get_streaming_flag int,get_streaming_delay int,get_num int,get_succeed_num int,get_retrans_num int,get_timeout_num int,get_max_ul_size int,get_min_ul_size int,get_max_dl_size int,get_min_dl_size int,intbuffer_fst_flag int,intbuffer_full_flag int,intbuffer_full_delay int,stall_num int,stall_duration int,streaming_dw_packets int,streaming_download_delay int,play_duration int,streaming_quality int,video_data_rate int,video_frame_rate int,video_codec_id string,video_width int,video_height int,audio_data_rate int,audio_codec_id string,streaming_filesize int,streaming_duratioin int,media_file_type int,play_state int,streaming_flag int,tcp_status_indicator int,disconnection_flag int,failure_code int,flag int,flow_sample_ratio int,tac string,eci string,tcp_syn_time int,tcp_syn_time_msel int,tcp_rtt_step1 int,tcp_ul_retrans_withpl int,tcp_dw_retrans_withpl int,tcp_ul_retrans_withoutpl int,tcp_dw_retrans_withoutpl int,tcp_ul_packages_withpl int,tcp_dw_packages_withpl int,tcp_ul_packages_withoutpl int,tcp_dw_packages_withoutpl int,upperlayer_ip_ul_packets int,upperlayer_ip_dl_packets int,downlayer_ip_ul_packets int,downlayer_ip_dl_packets int,upperlayer_ip_ul_fragments int,upperlayer_ip_dl_fragments int,downlayer_ip_ul_fragments int,downlayer_ip_dl_fragments int,service_dalay_msec int,valid_trans_duration int,air_port_duration int,radio_conn_times int,tcp_fst_syn_direction int,ran_ne_id int,ran_ne_user_ip string,homemcc string,homemnc string,homeprovince int,homecity int,service_id int,rcharging_class int,rcharge_flag int,prepaid_flag int,primary key(id)) mapped by (wf5 ,cols=[rk=cf1.rk,sid=cf1.sid,probeid=cf1.probeid,interfaceid=cf1.interfaceid,groupid=cf1.groupid,ggsn_id=cf1.ggsn_id,sgsn_id=cf1.sgsn_id,session_indicator=cf1.session_indicator,begin_time=cf1.begin_time,begin_time_msel=cf1.begin_time_msel,end_time=cf1.end_time,end_time_msel=cf1.end_time_msel,prot_category=cf1.prot_category,prot_type=cf1.prot_type,l7_carrier_prot=cf1.l7_carrier_prot,msisdn=cf1.msisdn,imsi=cf1.imsi,imei=cf1.imei,encrypt_version=cf1.encrypt_version,roaming_type=cf1.roaming_type,roam_direction=cf1.roam_direction,ms_ip=cf1.ms_ip,server_ip=cf1.server_ip,ms_port=cf1.ms_port,server_port=cf1.server_port,apn=cf1.apn,sgsn_sig_ip=cf1.sgsn_sig_ip,ggsn_sig_ip=cf1.ggsn_sig_ip,sgsn_user_ip=cf1.sgsn_user_ip,ggsn_user_ip=cf1.ggsn_user_ip,mcc=cf1.mcc,mnc=cf1.mnc,rat=cf1.rat,lac=cf1.lac,rac=cf1.rac,sac=cf1.sac,ci=cf1.ci,browser_type=cf1.browser_type,l4_ul_throughput=cf1.l4_ul_throughput,l4_dw_throughput=cf1.l4_dw_throughput,l4_ul_goodput=cf1.l4_ul_goodput,l4_dw_goodput=cf1.l4_dw_goodput,network_ul_traffic=cf1.network_ul_traffic,network_dl_traffic=cf1.network_dl_traffic,l4_ul_packets=cf1.l4_ul_packets,l4_dw_packets=cf1.l4_dw_packets,tcp_conn_states=cf1.tcp_conn_states,tcp_states=cf1.tcp_states,tcp_rtt=cf1.tcp_rtt,tcp_ul_outofsequ=cf1.tcp_ul_outofsequ,tcp_dw_outofsequ=cf1.tcp_dw_outofsequ,tcp_ul_retrans=cf1.tcp_ul_retrans,tcp_dw_retrans=cf1.tcp_dw_retrans,tcp_win_size=cf1.tcp_win_size,tcp_mss=cf1.tcp_mss,tcp_conn_times=cf1.tcp_conn_times,tcp_conn_2_failed_times=cf1.tcp_conn_2_failed_times,tcp_conn_3_failed_times=cf1.tcp_conn_3_failed_times,host=cf1.host,streaming_url=cf1.streaming_url,get_streaming_failed_code=cf1.get_streaming_failed_code,get_streaming_flag=cf1.get_streaming_flag,get_streaming_delay=cf1.get_streaming_delay,get_num=cf1.get_num,get_succeed_num=cf1.get_succeed_num,get_retrans_num=cf1.get_retrans_num,get_timeout_num=cf1.get_timeout_num,get_max_ul_size=cf1.get_max_ul_size,get_min_ul_size=cf1.get_min_ul_size,get_max_dl_size=cf1.get_max_dl_size,get_min_dl_size=cf1.get_min_dl_size,intbuffer_fst_flag=cf1.intbuffer_fst_flag,intbuffer_full_flag=cf1.intbuffer_full_flag,intbuffer_full_delay=cf1.intbuffer_full_delay,stall_num=cf1.stall_num,stall_duration=cf1.stall_duration,streaming_dw_packets=cf1.streaming_dw_packets,streaming_download_delay=cf1.streaming_download_delay,play_duration=cf1.play_duration,streaming_quality=cf1.streaming_quality,video_data_rate=cf1.video_data_rate,video_frame_rate=cf1.video_frame_rate,video_codec_id=cf1.video_codec_id,video_width=cf1.video_width,video_height=cf1.video_height,audio_data_rate=cf1.audio_data_rate,audio_codec_id=cf1.audio_codec_id,streaming_filesize=cf1.streaming_filesize,streaming_duratioin=cf1.streaming_duratioin,media_file_type=cf1.media_file_type,play_state=cf1.play_state,streaming_flag=cf1.streaming_flag,tcp_status_indicator=cf1.tcp_status_indicator,disconnection_flag=cf1.disconnection_flag,failure_code=cf1.failure_code,flag=cf1.flag,flow_sample_ratio=cf1.flow_sample_ratio,tac=cf1.tac,eci=cf1.eci,tcp_syn_time=cf1.tcp_syn_time,tcp_syn_time_msel=cf1.tcp_syn_time_msel,tcp_rtt_step1=cf1.tcp_rtt_step1,tcp_ul_retrans_withpl=cf1.tcp_ul_retrans_withpl,tcp_dw_retrans_withpl=cf1.tcp_dw_retrans_withpl,tcp_ul_retrans_withoutpl=cf1.tcp_ul_retrans_withoutpl,tcp_dw_retrans_withoutpl=cf1.tcp_dw_retrans_withoutpl,tcp_ul_packages_withpl=cf1.tcp_ul_packages_withpl,tcp_dw_packages_withpl=cf1.tcp_dw_packages_withpl,tcp_ul_packages_withoutpl=cf1.tcp_ul_packages_withoutpl,tcp_dw_packages_withoutpl=cf1.tcp_dw_packages_withoutpl,upperlayer_ip_ul_packets=cf1.upperlayer_ip_ul_packets,upperlayer_ip_dl_packets=cf1.upperlayer_ip_dl_packets,downlayer_ip_ul_packets=cf1.downlayer_ip_ul_packets,downlayer_ip_dl_packets=cf1.downlayer_ip_dl_packets,upperlayer_ip_ul_fragments=cf1.upperlayer_ip_ul_fragments,upperlayer_ip_dl_fragments=cf1.upperlayer_ip_dl_fragments,downlayer_ip_ul_fragments=cf1.downlayer_ip_ul_fragments,downlayer_ip_dl_fragments=cf1.downlayer_ip_dl_fragments,service_dalay_msec=cf1.service_dalay_msec,valid_trans_duration=cf1.valid_trans_duration,air_port_duration=cf1.air_port_duration,radio_conn_times=cf1.radio_conn_times,tcp_fst_syn_direction=cf1.tcp_fst_syn_direction,ran_ne_id=cf1.ran_ne_id,ran_ne_user_ip=cf1.ran_ne_user_ip,homemcc=cf1.homemcc,homemnc=cf1.homemnc,homeprovince=cf1.homeprovince,homecity=cf1.homecity,service_id=cf1.service_id,rcharging_class=cf1.rcharging_class,rcharge_flag=cf1.rcharge_flag,prepaid_flag=cf1.prepaid_flag])

and i found that in our clidriver, we count the time of println to cost time.

**Comment by scwf** [comment]
found that in bulkload and parallelizedbulkload, the time of save hfile cost much time.

**Comment by yzhou2001** [comment]
@scwf Another alternative is to stream reduce output to HBase region server. The idea I recall I discussed with you when you were in U.S. There will be some coding complexity to support streaming. Another issue with streaming is that it's hard to recover from a m/r failure. Does phoenix use streaming?

On the createtable side, Xinyun already checked in a fix. Could you test it?

**Comment by yzhou2001** [comment]
Phoenix's 500s is on presplit table or not? How about the query performance comparison using the latest code and after check the physical configurations/sizes as I recommended last time?

**Comment by scwf** [comment]
@yzhou2001, have test the newly checked in code and have the same result so here give xinyun the cmd.

regarding bulk load phoneix not use streaming, i found a litter different between my implementation and phoenix, not sure it will have big affect.

it seems phoenix not support presplit table(i mean first create a presplit table in hbase, the bulk loading into it). Phoenix's 500s is result of directly using the load cmd.

query performance:
If using no presplit table, the performance is very slower than phoenix, and enable code generation also the same result

if using pre split table, it is ing status

**Comment by yzhou2001** [comment]
If Phoenix does not support presplit (can it create SQL tables  on existing HBase tables? If so, then the presplit HBase table must be supported by it), then we should only compare non-presplit tables. Then a important check is to compare the physical data distribution: how many regions? how much data per region? ... before compare performances, particularly query performance. If all are close, then the query performance should be very close, because the query is really simple and it should be IO bound. And please use our latest software if not yet.

**Comment by scwf** [comment]
>can it create SQL tables on existing HBase tables?
no, seems not support this

**Comment by scwf** [comment]
>please use our latest software if not yet.

you mean new newly branch code?

**Comment by yzhou2001** [comment]
The latest code from the HW_HBase branch. As mentioned, I increased the fetch size from 100 to 1000 to match with Phoenix, which could improve query perf greatly.

**Comment by scwf** [comment]
Already using the latest code from HW_HBase branch this morning.

**Comment by scwf** [comment]
Found an interesting thing, when load the 1000000 records dataset with no pre split table
1 phoenix will create a hbase table which has 3 regions
2 our branch will create a hbase table which has only 1 region

**Comment by scwf** [comment]
And find another diff:
1 in phoenix, after create a table, the table in hbase has 0 region
2 in sparksqlhbase, after create a table, the table in hbase has 1 region

**Comment by yzhou2001** [comment]
The region difference will not only affect query but load performance as well. Please check to see how  Phoenix loading behaves so differently. Another comparison is with HBase's M/R-based bulk loading. Our bulk loading should be very close to HBase's because we clone our code and algorithm from there.

**Comment by scwf** [comment]
bug reports, test failed by ```build/sbt -Phive -Phadoop-2.3 -Phbase -Phive-thriftserver hbase/test ```
[info] JavaHbaseSuite:
[info] - aggregation with codegen
[info] - dsl simple select
[info] - metadata is propagated correctly
[info] - Query HBase native command execution result *** FAILED ***
[info]   java.lang.ClassNotFoundException: org.apache.spark.sql.hbase.KeyColumn
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
[info]   at java.lang.Class.forName0(Native Method)
[info]   at java.lang.Class.forName(Class.java:264)
[info]   at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:622)
[info]   at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1593)

**Comment by xinyunh** [comment]
Hi @scwf 

I have tested the sample you give me. It cost 17.057s on my machine and most of the time (15.943s) is checking the syntax. For now, I think we should not worry too much about this part since it hasn't really come into our part.

**Comment by scwf** [comment]
@xinyunh, you mean most time cost in parsing, right?

**Comment by scwf** [comment]
@xinyunh @yzhou2001 fixed the test warning

**Comment by xinyunh** [comment]
@scwf correct!

**Pull request closed without merging**
